#!/bin/bash
if [[ -e "$1" ]]; then
    source "$1"
    if [[ $? < 0 ]]; then
        printf "Include: Error: \"$1\": Unable to source file.\n"
    fi
else
    printf "Include: Error: \"$1\": File does not exist.\n" "$1"
fi
